// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string      `json:"id"`
	Content   string      `json:"content"`
	SenderID  string      `json:"senderId"`
	CreatedAt string      `json:"createdAt"`
	Reactions []*Reaction `json:"reactions"`
}

type Mutation struct {
}

type Query struct {
}

type Reaction struct {
	Emoji  string `json:"emoji"`
	UserID string `json:"userId"`
}

type Room struct {
	ID          string   `json:"id"`
	Type        string   `json:"type"`
	Name        *string  `json:"name,omitempty"`
	LastMessage *Message `json:"lastMessage,omitempty"`
	UnreadCount int32    `json:"unreadCount"`
	Members     []*User  `json:"members"`
}

type Subscription struct {
}

type TypingEvent struct {
	UserID   string `json:"userId"`
	IsTyping bool   `json:"isTyping"`
}

type User struct {
	ID          string  `json:"id"`
	DisplayName string  `json:"displayName"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	Status      string  `json:"status"`
}
